### ISSUE TITLE
running example.cpp

### ISSUE THREAD

**Issue by Soficlyopathrmiss** [lemire/FastPFor#21]
Hi,
I want to display some values of the compressed and decompressed vectors in the example.cpp so i added these lines:
for(uint32_t i = 0; i < 8;i ++)
       std::cout<<"compressed_vector " << i <<" " << compressed_output.data()[i]<<std::endl;
...........
for(uint32_t i = 0; i < 8;i ++)
       std::cout<<"Dompressed_vector " << i <<" " << mydataback.data()[i]<<std::endl;
but the result is
sofi@ubuntu:~/FastPFor$ ./example
compressed_vector 0 9984
compressed_vector 1 3
compressed_vector 2 0
compressed_vector 3 0
compressed_vector 4 183
compressed_vector 5 2517106944
compressed_vector 6 738787840
compressed_vector 7 167903426
You are using 0.294 bits per integer. 
Dompressed_vector 0 0
Dompressed_vector 1 0
Dompressed_vector 2 0
Dompressed_vector 3 0
Dompressed_vector 4 0
Dompressed_vector 5 0
Dompressed_vector 6 0
Dompressed_vector 7 0
how can i get these values correctly? What is the problem ?
Thanks in advance.

**Comment by lemire** [comment]
I will get back to you soon.

**Comment by lemire** [comment]
I think that everything is well.

We are compressing 10,000 values, and then recovering these same 10,000 values.


I suspect that you somehow got the impression that we are compressing one thing and recovering another. That is not the case.



To check manually that the library works, you could first print out some of the initial values : 
```c++
for(uint32_t i = 0; i < N;i += 150)
  std::cout<<"initial_vector " << i <<" " << mydata[i]<<std::endl;
```

Of course, this does not display all 10,000 values. You can get this desired result if you change `i+= 150` by `i++`, but it will fill your screen.

(You could also change the example so that it does not compress 10,000 values... but I guess that you want to be convinced here, by manual inspection, that the result is correct.)

Later, you can check that the recovered values match the original values like so:

```c++
for(uint32_t i = 0; i < N;i += 150)
  std::cout<<"Compressed_vector " << i <<" " << mydataback[i]<<std::endl;
```

Again, if you want to display all 10,000 values, you can change `i+= 150` by `i++`, but it will fill your screen.

In any case, what matters is that `mydataback` and `mydata` have identical content.

There is little sense in manually inspecting the content of  compressed_output unless you are familiar with the algorithms. Most users should not care about the compressed binary format.


I hope this helps. I am closing this issue.

**Comment by gevago01** [comment]
I understand that the content of the compressed_vector should not be legible (for most users), but does the API allow queries directly on the compressed vector? For example, checking whether a particular bit is set.
