### ISSUE TITLE
Understanding performance

### ISSUE THREAD

**Issue by senior7515** [lemire/FastPFor#37]
I didn't find a mailing list, but wanted to evaluate this encoding - see: 

https://gist.github.com/db0db4996ed4584ee45ee692db1bac27

```
Benchmark                                             Time           CPU Iterations
------------------------------------------------------------------------------------
BM_fast_pfor_simd_encode/256/256                    827 ns        829 ns     845117
BM_fast_pfor_simd_encode/512/512                   1279 ns       1281 ns     551218
BM_fast_pfor_simd_encode/1024/1024                 2102 ns       2104 ns     333331
BM_fast_pfor_simd_encode/131072/131072           238223 ns     237819 ns       2938
BM_fast_pfor_simd_encode/134217728/134217728  260439758 ns  260120405 ns          3

BM_varint_encode/256/256                            172 ns        172 ns    4059510
BM_varint_encode/256/256                            174 ns        174 ns    4003933
BM_varint_encode/512/512                            360 ns        360 ns    1942246
BM_varint_encode/1024/1024                          730 ns        729 ns     940887
BM_varint_encode/131072/131072                   132649 ns     132549 ns       5286
BM_varint_encode/134217728/134217728          193145278 ns  193002870 ns          4


```

In this example, a simple varint, is 30% faster than fastPfor - SIMD128 version. 

Is this expected? 

Optimization level -O2

**Comment by senior7515** [comment]
SIMD version is much faster than non-simd 

```
BM_fast_pfor_encode/256/256                         868 ns        870 ns     801262
BM_fast_pfor_encode/512/512                        1385 ns       1387 ns     502030
BM_fast_pfor_encode/1024/1024                      2360 ns       2360 ns     293444
BM_fast_pfor_encode/131072/131072                265570 ns     265118 ns       2636
BM_fast_pfor_encode/134217728/134217728       305674691 ns  305292972 ns          2


```

**Comment by lemire** [comment]
We offer simple benchmarks...

```
make codecs
./codecs --clusterdynamic
./codecs --uniformdynamic
```

Otherwise,  you can test with real data that you care about.

In any case, if you have an issue with trying to understand the performance, please make sure to open an issue where you document your data input characteristics and the testing procedure.

Speaking for myself, I cannot make sense of columns of timings. I need explanations as to what is being compressed or uncompressed and how.

**Comment by lemire** [comment]
I closed the issue. Please feel free to re-open, but please study the benchmarks we offer, first.

**Comment by senior7515** [comment]
ok, will make detailed report. 

The gist is representative of how I planned to use the lib. 

I have a bunch of offsets, monotonically increasing - offsets into arrays.

the second column shows the time the function took to run under google benchmark. 

In any case, let me study the benchmarks included and I'll follow up w/ a report. 

Thanks!

**Comment by lemire** [comment]
@senior7515 

> I have a bunch of offsets, monotonically increasing - offsets into arrays.

Please see...

https://github.com/lemire/FastPFor#working-with-sorted-lists-of-integers

**Comment by lemire** [comment]
@senior7515 

- You need to report the compression ratio as well (otherwise memcpy will kick your ass all the time).
- I recommend reporting the results in terms of numbers of integers being compressed or uncompressed per second (or per cpu cycles). Or you can reverse that and report the number of ns per integer. Absolute running times are not so useful.
- You need to use sensible data inputs. Compressing the numbers 0,1,2,... does not make much sense as a problem. 
- If the data is monotonic, you need differential coding.
- varint is indeed pretty fast under the right conditions.
- If you like varint, you may want to check out https://lemire.me/blog/2017/09/27/stream-vbyte-breaking-new-speed-records-for-integer-compression/

**Comment by senior7515** [comment]
thanks! I had read the Reame a while ago, and honestly... i forgot... my bad. 

Makes sense for reporting. Thanks!

**Comment by lemire** [comment]
+1

**Comment by lemire** [comment]
>  I had read the Reame a while ago, and honestly... i forgot...

Sure.

Your approach to benchmarking is more modern that what we have... so maybe you could issue a pull request eventually? But I submit to you that creating a solid benchmark that is representative takes a bit more than a few lines.

**Comment by senior7515** [comment]
I agree. I was just trying to get a sense for this, i.e.: hello-world. 

The use case is that i have a huge buffer - possibly 2 GB with small messages in it, say 100 bytes. 

I wanted to store the indexes in a compressed format to it. 

Anyway, let me put some more effort into the benchmark, with an actual data format and layout and see what the difference is. 

I have a couple of changes to this lib already, so I could incldue them in my build.

**Comment by lemire** [comment]
That's my kind of problem. Please stay in touch.
